name: Ion Hash DotNet CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]        # add other OSes later
        dotnet: ['2.1']

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with: 
          submodules: recursive
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Project Build
        run: dotnet build --configuration Release
      - name: ls
        run: ls && ls Amazon.IonHashDotnet && ls Amazon.IonHashDotnet/bin && Amazon.IonHashDotnet/bin/Release
      - name: Project Test
        run: dotnet test --configuration Release --no-build --no-restore --verbosity normal 
